version: '2'
services:
  onetimesecret:
    container_name: ots
    # image: 'dismantl/onetimesecret'
    build: .
    restart: always
    ports:
      - '7143:7143'
    volumes:
      - './config:/etc/onetime/config'
      - './redis:/var/run/redis'
    environment:
      - OTS_NAME=John Doe
